export const names = [
    {
        name: 'mohammed'
    },
    {
        name: 'mohammed'
    },
    {
        name: 'mohammed'
    },
    {
        name: 'mohammed' 
    },
    {
        name: 'mohammed'
    },
]


export const posts = [
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    },
    {
        name: 'CraigAdderley',
        avatar: 'https://images.pexels.com/users/avatars/657879/craig-adderley-766.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Mount Bethel, PA, USA',
        postimg: 'https://images.pexels.com/photos/1671878/pexels-photo-1671878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '130',
        desc: 'Great christmas with my family this year . ',
        tags: '',
        name1: 'Zayyanu Suleiman',
        comment1: '🙌🙌🙌🙌',
        comment2: '',
        name2: '',
        date: '2 days ago'
    },
    {
        name: 'JillWellington',
        avatar: 'https://images.pexels.com/users/avatars/1638660/jill-wellington-390.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'Michigan',
        postimg: 'https://images.pexels.com/photos/3334511/pexels-photo-3334511.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
        likes: '12',
        desc: 'What a amazing weather ! ',
        tags: '',
        name1: 'Devraj Nair',
        comment1: 'WOOOOOOOOOW',
        comment2: '',
        name2: '',
        date: '3 days ago'
    },
    {
        name: 'Emiliano Arano',
        avatar: 'https://images.pexels.com/users/avatars/546733/emiliano-arano-474.jpeg?w=256&h=256&fit=crop&auto=compress',
        place:'',
        postimg: 'https://images.pexels.com/photos/4802300/pexels-photo-4802300.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        likes: '170',
        desc: '',
        tags: '',
        name1: 'Jack',
        comment1: 'Amazing !',
        comment2: '',
        name2: '',
        date: '1 days ago'
    }

]